spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.2.248:3306/jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema:
      - classpath:datasource/department.sql
    initialization-mode: always